### ISSUE TITLE
Improve script blocking 

### ISSUE THREAD

**Issue by alpipego** [norcross/airplane-mode#98]
Instead of setting the `src` to an error object on the script loader tag (where a string is expected), I propose 

* setting the `src` to an empty string
* adding the error as data on the `_WP_Dependency` object 

I'd be happy to PR this.

**Comment by norcross** [comment]
that’s how it functioned initially and it was changed for other reasons, so I don’t think that’ll be added.

**Comment by johnbillion** [comment]
Is this causing a problem somewhere? I'd like to know if it is. The error object implements the `__tostring()` method which means it can be treated as a string.

https://github.com/norcross/airplane-mode/blob/eb695e439fe26a6a3ac0aca83d0f7e07fb6669ad/airplane-mode.php#L1267-L1275

**Comment by alpipego** [comment]
`$data['return']` is a empty string.

`return $this->get_error_message();` gets the error message, but WordPress then turns it into `http://Airplane%20Mode%20blocked%20script`...

**Comment by alpipego** [comment]
And the method should be camelCased right? `__toString()`

**Comment by johnbillion** [comment]
Thanks for the info. I think what you're asking for is already in place.

The empty string in `$data['return']` is intentional -- this is what sets the script's `src` to an empty string (when it's read as a string), and prevents WordPress from loading the script.

However, because the `_WP_Dependency->src` property is actually an error object, it can be read as one too: `$dependency->src->get_error_message()`.

This was introduced in #74 and its use can be seen in the Query Monitor plugin here: https://github.com/johnbillion/query-monitor/blob/a171c1f503712f591ec0feb14c74b192756d807e/output/html/assets.php#L138-L152

**Comment by alpipego** [comment]
Ok, thanks for the explanation.

I don't get why it had to be done in such a counterintuitive way though, instead of using the options already in place on the `_WP_Dependency` (i.e. add the error object to the data field).

**Comment by johnbillion** [comment]
I did consider that originally (using `->add_data()`) but it technically pollutes the data that is already stored against the handle, which could be unexpected and could bubble up elsewhere. I don't think it's any more or less intuitive to use such a data store as a location for debugging information.

**Comment by alpipego** [comment]
I disagree with 

> it pollutes the data [...] against the handle, which could be unexpected and could bubble up elsewhere

The WP docs just say 

> `Extra data to supply to the handle.`

So I don't see any pollution there.
